version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: node_app

    ports:
      - "3000:3000"
    depends_on:
      - mongo
    # environment:
    #   - MONGO_URI=mongodb://mongo:27017/mydatabase
    #   - PORT=3000
    volumes:
      - ./.env:/app/.env:ro


volumes:
  mongo_data:
